params:
 - params.yaml

stages:
  split_data:
    cmd:
      - pwd
      # - export PYTHONPATH=${host.masterdir}:$PYTHONPATH
      # - echo $PYTHONPATH
      - echo "SPLIT DATA ${task.name}"
      - mkdir -p data/${task.name}/
      - PYTHONPATH=src uv run --active python src/surfpro/dataloader.py
    params:
      - task
      - host
    deps:
      - src/surfpro/dataloader.py
      - data/surfpro_train.csv
      - data/surfpro_test.csv
    outs:
      - data/${task.name}/df_raw.csv
      - data/${task.name}/surfpro.pkl

  train:
    cmd:
      - rm -fR out/${task.name}
      - mkdir -p out/${task.name}/models
      - echo "TRAIN ${task.name}"
      - PYTHONPATH=src uv run --active python scripts/train_model.py
    params:
      - task
      - model
      - host
    deps:
      - data/${task.name}/surfpro.pkl
      - src/surfpro/model.py
      - scripts/train_model.py
    outs:
      - out/${task.name}/models/:
          persist: true
      - out/${task.name}/metrics.json
      - out/${task.name}/test_preds_folds.csv

  predict:
    cmd:
      - echo "PREDICT ${task.name}"
      - PYTHONPATH=src uv run --active python scripts/fill_table.py
    params:
      - task
      - model
      - host
    deps:
      - src/surfpro/model.py
      - out/${task.name}/models
      - scripts/fill_table.py
      - data/${task.name}/surfpro.pkl
      - data/${task.name}/df_raw.csv
    outs:
      - out/${task.name}/df_ensemble_preds.csv
      - out/${task.name}/filled_table_merged.csv

  evaluate:
    cmd:
      - echo "EVALUATE ${task.name}"
      - PYTHONPATH=src uv run --active python scripts/evaluate_model.py
    params:
      - task
      - model
      - host
    deps:
      - src/surfpro/model.py
      - scripts/evaluate_model.py
      - data/${task.name}/df_raw.csv
      - out/${task.name}/df_ensemble_preds.csv
      - out/${task.name}/test_preds_folds.csv
    outs:
      - out/${task.name}/results_test_metrics.json
      - out/${task.name}/eval_metrics.json
      - out/${task.name}/eval_metrics.csv

  plot:
    cmd:
      - echo "PLOTTING ${task.name}"
      - mkdir -p out/${task.name}/plots/parity
      - PYTHONPATH=src uv run --active python scripts/plot_predictions.py
      - mkdir -p ${host.masterdir}/results/${task.name}/
      - mkdir -p ${host.masterdir}/results/plots/
      - cp params.yaml out/${task.name}/params.yaml
      - cp -r out/${task.name}/.
        ${host.masterdir}/results/${task.name}/${model.name}-${task.name}/
    params:
      - task
      - model
      - host
    deps:
      - scripts/plot_predictions.py
      - data/${task.name}/df_raw.csv
      - out/${task.name}/df_ensemble_preds.csv
    outs:
      - out/${task.name}/plots/:
          persist: true
