task:
  name: all
  props:
  - pCMC
  - AW_ST_CMC
  - Gamma_max
  - Area_min
  - Pi_CMC
  - PC20
  units:
  - ''
  - mN/m
  - mol/m^2 * 1e6
  - nm^2
  - mN/m
  - ''
  data_seed: 42
  n_splits: 2
  scale: true
model:
  name: AttentiveFP-64d
  n_epochs: 10
  seed: 42
  n_batch: 64
  hidden_channels: 64
  out_channels: 128
  num_layers: 2
  num_timesteps: 2
  dropout: 0.1
  featurize: graph
host:
  masterdir: /home/stefan/phd/SurfPro
  workdir: .
  device:
  - 0
